better user management
+ fix for https://github.com/ncarlier/webhookd/issues/29

diff --git a/gitea/DEBIAN/postrm b/gitea/DEBIAN/postrm
--- a/gitea/DEBIAN/postrm
+++ b/gitea/DEBIAN/postrm
@@ -1,9 +1,15 @@
 #!/usr/bin/env bash
 case "$1" in
-    remove)
-        deluser git --remove-home
-        echo "GIT user removed"
+    purge)
+        if [ -x "$(command -v deluser)" ]; then
+          deluser --quiet --system --remove-home git > /dev/null || true
+          echo "GIT user removed"
+        else
+          echo >&2 "not removing git system account because deluser command was not found"
+        fi        
         ;;
     *)
         ;;
 esac
+
+exit 0
diff --git a/webhookd/DEBIAN/postrm b/webhookd/DEBIAN/postrm
--- a/webhookd/DEBIAN/postrm
+++ b/webhookd/DEBIAN/postrm
@@ -4,10 +4,13 @@ case "$1" in
         ;;
     purge)
         rm /etc/webhookd.env
+        if [ -x "$(command -v deluser)" ]; then
+          deluser --quiet --system webhookd > /dev/null || true
+        else
+          echo >&2 "not removing webhookd system account because deluser command was not found"
+        fi
         ;;
     *)
-        deluser webhookd
-        echo "WEBHOOKD user removed"
         ;;
 esac
 
